// Generated by CoffeeScript 1.10.0
(function() {
  var $blogList, $blogListTemplate, BlogCollection, BlogModel, blogView, blogViews, blogs, johnBlog, karlBlog;

  BlogModel = Backbone.Model.extend({
    defauls: {
      author: '',
      title: '',
      url: ''
    }
  });

  BlogCollection = Backbone.Collection.extend();

  karlBlog = new BlogModel({
    author: "Karl",
    titl: "Karl\'s Blog",
    url: "http://karl.com/blog"
  });

  johnBlog = new BlogModel({
    author: "John",
    titl: "John\'s Blog",
    url: "http://john.com/blog"
  });

  blogs = new BlogCollection([karlBlog, johnBlog]);

  $blogList = $('.blog-list');

  $blogListTemplate = $('.blog-list-template');

  blogView = new Backbone.View.extend({
    model: new BlogModel,
    tagName: 'tr',
    initialize: function() {
      return this.template = $blogListTemplate.html();
    },
    render: function() {
      var blogData;
      blogData = this.model.toJSON();
      return this.$el.html(this.template(blogData));
    }
  });

  blogViews = new Backbone.View.extend({
    model: blogs,
    el: $blogList,
    initialize: function() {
      return this.model.on('add', this.render(), this);
    },
    render: function() {
      var self;
      self = this;
      this.$el.html('');
      return _.each(this.model.toArray(), function(blog) {
        blogView = new blogView({
          model: blog
        });
        return self.$el.append(blogView.render().$el);
      });
    }
  });

  $(document).ready(function() {
    var $blogForm;
    $blogForm = $('form[name=blog-form]');
    return $blogForm.on('submit', function(e) {
      var $this, sFormData;
      e.preventDefault();
      $this = $(this);
      sFormData = $this.serializeArray();
      return console.log(typeof JSON.stringify(sFormData));
    });
  });

}).call(this);
